### ISSUE TITLE
Why not use GitHub's built in "Releases" feature?

### ISSUE THREAD

**Issue by AndrewGuenther** [MediaBrowser/Emby.Releases#13]
Is there a reason that all of these releases live in this repository rather than using the Github's "Releases" feature? It seems to target exactly what you're trying to do here and also give more traceability as to what commits produced which releases.

**Comment by LukePulverenti** [comment]
We do. We tag releases here:

https://github.com/MediaBrowser/MediaBrowser/releases

These zips are strictly for some of our linux package maintainers who prefer to grab a prebuilt zip rather than incorporate building from source into their scripts. Similarly, there are also mac zips here. If there's a way we can tie multiple downloads into a github release, then we're all for that if you'd like to help out.

**Comment by danergo** [comment]
How can I build the mono package for myself? Is there any documentation for that?
(prebuilt package is named: MediaBrowser.Mono.zip).

Thanks

**Comment by LukePulverenti** [comment]
I notice we can now attach our own binaries to github releases, so we're going to be switching to that:

https://github.com/MediaBrowser/Emby/releases/tag/3.0.5781.1
